name: E2E Tests

on:
  pull_request:

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Package native executable
        run: mvn clean package -Pnative -DdockerBuild=true
      - name: Verify binary shows help message
        run: |
          ./target/github-dependents-scraper-uber 2>&1 | grep "Missing required parameter: 'URL'"